<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!"><b>C</b></a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item dropdown">
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#!">All Products</a></li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Product section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5" id=item_view>
            <?php
                echo "<div class='row gx-4 gx-lg-5 align-items-center'>
                <div class='col-md-6'><img class='card-img-top mb-5 mb-md-0' src=".$data["image"]." alt='...' /></div>
                <div class='col-md-6'>
                    <div class='small mb-1'>".$data["name"]."</div>
                    <h1 class='display-5 fw-bolder'>".$data["company"]."</h1>
                    <div class='fs-5 mb-5'>
                        <span>$".$data["price"]."</span>
                    </div>
                    <p class='lead'>Lorem ipsum dolor sit amet consectetur".
                    " adipisicing elit. Praesentium at dolorem quidem modi.".
                    " Nam sequi consequatur obcaecati excepturi alias magni, accusamus".
                    " eius blanditiis delectus ipsam minima ea".
                    " iste laborum vero?</p>
                </div>";
            ?>
            </div>
        </div>
    </section>

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
        </div>
    </footer>
</body>