<h1>Product Table</h1>

<h3>Add</h3>
<form action="../admin/add" method="post">
    <label for="name">Name</label>
    <input type="text" id="name" name="name" class="form-control">
    <label for="company">Company</label>
    <input type="text" id="company" name="company" class="form-control">
    <label for="quantity">Quantity</label>
    <input type="text" id="quantity" name="quantity" class="form-control">
    <label for="name">Price</label>
    <input type="text" id="price" name="price" class="form-control">
    <label for="name">Image</label>
    <input type="text" id="image" name="image" class="form-control">
    <button class="btn btn-primary my-3">Add</button>
</form>

<h3>Table</h3>
<table class="table">
    <caption>Product Table</caption>
    <thead>
        <tr>
            <th>Name</th>
            <th>Company</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Image</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $value) {
            $txt .= '<tr>
            <td>'.$value->name.'</td> <td>'.$value->company.'</td> <td>'.$value->quantity.'</td>
            <td>'.$value->price.'</td><td>'.$value->image.'</td>
            <td><a href="../admin/edit?id='.$value->_id.'" Class="btn btn-warning">Edit</a></td>
            <td><a href="../admin/delete?id='.$value->_id.'" Class="btn btn-danger">Delete</a></td>
            </tr>';
        }
        echo $txt;
        ?>
    </tbody>
</table>